workspace 'NewsUIKit.xcworkspace'

platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

def newsUIKit_pods
  pod 'AWNewsAPIKit'
  pod 'JXSegmentedView', ">=1.0.0"
  pod 'SnapKit'
  pod 'Kingfisher'
end

target 'NewsUIKit' do
  newsUIKit_pods
end

target 'NewsUIKitDemo' do
  newsUIKit_pods
end
